### ISSUE TITLE
Unable to run container based on Dockerfile provided

### ISSUE THREAD

**Issue by dbolger** [josephspurrier/polarbearblog#9]
When using the provided Dockerfile, I was able to pass in the `.env` environment variables in the `docker run` command, however, after solving that I'm getting an error stating that the `storage/site.json` file isn't being found.

```
docker run --env-file ./.env --name pbb -p 8080:8080 pbb
main.go:23: open storage/site.json: no such file or directory
```

This file is present in the root of the directory at `./storage/site.json`. I've noticed the `WORKDIR` in the Dockerfile image is set to app. I tried moving the storage directory to the app directory, but that gave the same error.

**Comment by dbolger** [comment]
Perhaps I need to specify a volume when running the container

**Comment by dbolger** [comment]
Yeap, this was the issue. Was able to configure the image successfully in a docker-compose file:
```
  blog:
    container_name: pbb-personal-blog
    env_file:
      - ./.env
    image: pbb
    ports:
      - "8080:8080"
    volumes:
      - /srv/polarbearblog/storage:/app/storage
```
